package selectors

const (
	Welcome                          = ".welcome"
	Logout                           = ".logout"
	Task                             = "li.task"
	TaskCompleted                    = "li.task.completed"
	TaskToggle                       = "li.task .toggle"
	TaskDelete                       = "li.task .delete"
	TaskList                         = "ul.tasks"
	Errors                           = ".errors"
	LoginForm                        = "form.login"
	LoginFormSubmit                  = "form.login input[type=\"submit\"]"
	LoginFormEmail                   = "form.login input[name=\"email\"]"
	LoginFormPassword                = "form.login input[name=\"password\"]"
	RegisterForm                     = "form.register"
	RegisterFormSubmit               = "form.register input[type=\"submit\"]"
	RegisterFormEmail                = "form.register input[name=\"email\"]"
	RegisterFormName                 = "form.register input[name=\"name\"]"
	RegisterFormPassword             = "form.register input[name=\"password\"]"
	RegisterFormPasswordConfirmation = "form.register input[name=\"passwordConfirmation\"]"
	TaskForm                         = "form.createTask"
	TaskFormName                     = "form.createTask input[name=\"name\"]"
	TaskFormDescription              = "form.createTask input[name=\"description\"]"
	TaskFormCollaborator1            = "form.createTask input[name=\"collaborator1\"]"
	TaskFormCollaborator2            = "form.createTask input[name=\"collaborator2\"]"
	TaskFormCollaborator3            = "form.createTask input[name=\"collaborator3\"]"
	TaskFormSubmit                   = "form.createTask input[type=\"submit\"]"
)
